# SPDX-FileCopyrightText: 2025 Delos Data Inc
# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'               # matches releases like 1.0.0
      - '[0-9]+.[0-9]+.[0-9]+-[a-z]+.[0-9]+' # matches pre-releases like 1.0.0-rc.1

permissions: read-all

jobs:
  build-profiler-container:
    name: Build and Release Profiler Container
    uses: ./.github/workflows/nccl-profiler-plugin-container.yml
    with:
      force_build: true
    secrets: inherit

  build-gpu-pcie-exporter-container:
    name: Build and Release GPU PCIe Exporter Container
    uses: ./.github/workflows/gpu-pcie-exporter-container.yml
    with:
      force_build: true
    secrets: inherit

  build-pipeline-analyzer-container:
    name: Build and Release Pipeline Analyzer Container
    uses: ./.github/workflows/pipeline-analyzer-container.yml
    with:
      force_build: true
    secrets: inherit

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build-profiler-container, build-gpu-pcie-exporter-container, build-pipeline-analyzer-container]
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.5.0
        with:
          draft: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
